"""
URL building and templating with Jinja in Flask

Jinja is a templating language

Project is to build a simple blog with posts based on the template
"""

from flask import Flask
from flask import render_template
import random
import datetime

app = Flask(__name__)

@app.route("/")
def website():
    random_number = random.randint(1, 50)
    current_year = datetime.date.today().strftime("%Y")
    return render_template("index.html", num=random_number, year=current_year)

if __name__ == "__main__":
    app.run(debug=True)


# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Jinja Ninja</title>
#     <link rel="stylesheet" href="static/style.css" />
# </head>
# <body>
#     <h1>I am Jinja</h1>
#     <p>This is using Jinja and Python to calculate 5 * 6 = {{ 5 * 6 }}</p>
#     <p>Random number between 1 and 50 generated by randint: {{ num }}</p>
# </body>
# <footer>
#     <p>© {{ year }} - built by James. The year is dynamically generated with the timedate module.</p>
# </footer>
# </html>

from flask import Flask
from flask import render_template
import random
import datetime

app = Flask(__name__)

@app.route("/")
def website():
    random_number = random.randint(1, 50)
    current_year = datetime.date.today().strftime("%Y")
    return render_template("index.html", num=random_number, year=current_year)

@app.guess("/guess")
def guess()

print(f"Hi James")
gender = "https://api.agify.io?<name>"
print(f"I think you are {gender}")
age = "https://api.genderize.io?<name>"
print(f"And maybe {age} years old")


if __name__ == "__main__":
    app.run(debug=True)


"""
Guess Example
"""

from flask import Flask
from flask import render_template
import random
import datetime
import requests

app = Flask(__name__)

@app.route("/")
def website(): 
    # number
    random_number = random.randint(1, 50)
    
    # year
    current_year = datetime.date.today().strftime("%Y")
    return render_template("index.html", 
                           num=random_number, 
                           year=current_year
                           )

@app.route("/guess/<name>")
def guess(name):
    # name
    upper_name = name.title()

    # gender
    gender_response = requests.get(f"https://api.genderize.io?name={name}")
    guessed_gender = gender_response.json()["gender"]

    # age
    age_response = requests.get(f"https://api.agify.io?name={name}")
    guessed_age = age_response.json()["age"]

    # year
    random_number = random.randint(1, 50)
    current_year = datetime.date.today().strftime("%Y")

    return render_template("guess.html", 
                           name = upper_name, 
                           gender = guessed_gender, 
                           age = guessed_age, 
                           year = current_year
                           )

@app.route("/blog/<num>")
def get_blog(num):
    #blogs
    blogs_response = requests.get("https://api.npoint.io/c790b4d5cab58020d391")
    all_posts = blogs_response.json()
    return render_template("blog.html", 
                           posts = all_posts
                            )

if __name__ == "__main__":
    app.run(debug=True)

# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Jinja Ninja Blog</title>
#     <link rel="stylesheet" href="static/style.css" />
# </head>
# <body>
#     <h1>I am Jinja Blog</h1>
#     {% for blog_post in posts: %}
#         <h2>{{ blog_post["title"] }}</h1>
#         <h3>{{ blog_post["subtitle"] }}</h2>
#     {% endfor %}
# <a href="{{ url_for('get_blog', num=3) }}">Go To Blog</a>
# </body>
# <footer>
# </footer>
# </html>